### ISSUE TITLE
Reference app doesn't build with Android Studio 1.0.1

### ISSUE THREAD

**Issue by nomath4u** [RadiusNetworks/campaignkit-reference-android-studio#1]
Got the following error when trying to build on Android Studio 1.0.1. Already changed `build.gradle` from `runProguard` to `minifyEnabled`.

```
Information:Gradle tasks [:app:assembleDebug]
:app:preBuild
:app:compileDebugNdk UP-TO-DATE
:app:preDebugBuild
:app:checkDebugManifest
:app:preReleaseBuild
:app:prepareComAndroidSupportAppcompatV71910Library UP-TO-DATE
:app:prepareComAndroidSupportSupportV42100Library UP-TO-DATE
:app:prepareComGoogleAndroidGmsPlayServices6587Library UP-TO-DATE
:app:prepareComRadiusnetworksCampaignkitAndroidV003Library UP-TO-DATE
:app:prepareDebugDependencies
:app:compileDebugAidl UP-TO-DATE
:app:compileDebugRenderscript UP-TO-DATE
:app:generateDebugBuildConfig UP-TO-DATE
:app:generateDebugAssets UP-TO-DATE
:app:mergeDebugAssets UP-TO-DATE
:app:generateDebugResValues UP-TO-DATE
:app:generateDebugResources UP-TO-DATE
:app:mergeDebugResources UP-TO-DATE
:app:processDebugManifest UP-TO-DATE
:app:processDebugResources UP-TO-DATE
:app:generateDebugSources UP-TO-DATE
:app:compileDebugJava
:app:preDexDebug
:app:dexDebug
UNEXPECTED TOP-LEVEL EXCEPTION:
Error:Execution failed for task ':app:dexDebug'.
> com.android.ide.common.internal.LoggedErrorException: Failed to run command:
    /home/chris/Android/sdk/build-tools/19.1.0/dx --dex --no-optimize --output /home/chris/Android/projects/campaignkit-reference-android-studio/app/build/intermediates/dex/debug /home/chris/Android/projects/campaignkit-reference-android-studio/app/build/intermediates/classes/debug /home/chris/Android/projects/campaignkit-reference-android-studio/app/build/intermediates/pre-dexed/debug/support-annotations-21.0.0-f49c6d66b6f14323b8faedd99e46c3e14e71a4b7.jar /home/chris/Android/projects/campaignkit-reference-android-studio/app/build/intermediates/pre-dexed/debug/classes-ceea5c27a4a1bf8cc0e619d408569cfae8533e8f.jar /home/chris/Android/projects/campaignkit-reference-android-studio/app/build/intermediates/pre-dexed/debug/greendao-1.3.7-6c498aff8d1fb5616cf0ea0cbe99f38d2d80c3de.jar /home/chris/Android/projects/campaignkit-reference-android-studio/app/build/intermediates/pre-dexed/debug/android-beacon-library-ffa37a89c08836a16b1134d8fce7aa6ad72529cf.jar /home/chris/Android/projects/campaignkit-reference-android-studio/app/build/intermediates/pre-dexed/debug/proximitykit-android-c0e3650d90bff6197187381b5fc6d393eeade830.jar /home/chris/Android/projects/campaignkit-reference-android-studio/app/build/intermediates/pre-dexed/debug/internal_impl-21.0.0-b53ad8baf959378e6439c44430e2e1f27958606c.jar /home/chris/Android/projects/campaignkit-reference-android-studio/app/build/intermediates/pre-dexed/debug/classes-0e606f7952380f93fca04257b1e29e129e2d84a9.jar /home/chris/Android/projects/campaignkit-reference-android-studio/app/build/intermediates/pre-dexed/debug/android-support-v4-1ede90a8da1d101cbb51a012010881fa8bf3d99d.jar /home/chris/Android/projects/campaignkit-reference-android-studio/app/build/intermediates/pre-dexed/debug/classes-9fe50ada019ca866c655845e883c663315713696.jar /home/chris/Android/projects/campaignkit-reference-android-studio/app/build/intermediates/pre-dexed/debug/classes-b92ab3f3b17d99fc7ff993bbb7c9e82250aef8c8.jar
  Error Code:
    2
  Output:
    UNEXPECTED TOP-LEVEL EXCEPTION:
    com.android.dex.DexException: Multiple dex files define Landroid/support/annotation/AnimRes;
        at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:594)
        at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:552)
        at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:533)
        at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:170)
        at com.android.dx.merge.DexMerger.merge(DexMerger.java:188)
        at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:439)
        at com.android.dx.command.dexer.Main.runMonoDex(Main.java:287)
        at com.android.dx.command.dexer.Main.run(Main.java:230)
        at com.android.dx.command.dexer.Main.main(Main.java:199)
        at com.android.dx.command.Main.main(Main.java:103)
Information:BUILD FAILED
Information:Total time: 6.652 secs
Information:1 error
Information:0 warnings
Information:See complete output in console
```

**Comment by cupakromer** [comment]
Closing AS is on v3 now and the ref app works with it.
